[package]
name = "hello-wasm-tutorial"
version = "0.1.0"
edition = "2021"
authors = ["Daiki Nakashima"]
description = "WebAssembly tutorial"
license = "MIT"
repository = "https://github.com/Daiki48/hello-wasm-tutorial"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
